name = "Bundeswehr Waffenkammer"
prefix = "pbw"
author = "Herr_KaLeun, Lemonberries, Timi007"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "LICENSE",
    "pbw_waka_logo.paa",
    "meta.cpp"
]
folder_optionals = false

modname = "BW_Waffenkammer"
key_name = "pbw_waka_{{version}}"
authority = "pbw_waka_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip BW_Waffenkammer_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "{{git \"id 8\"}}"
