name = "BW_Waffenkammer"
mainprefix = ""
prefix = "pbw"
author = "Herr_KaLeun, Lemonberries, Timi007"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "pbw_waka_logo.paa",
    "meta.cpp"
]

[signing]
authority = "pbw_waka"

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "BW_Waffenkammer"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057" # ACE3's Workshop ID
]
